### PR TITLE
ci: bump Xcode from 26.3 to 26.6 for iOS library builds

### PR DESCRIPTION
**Pull request by hryhoriiK97**
## Summary

Bumps iOS nightly builds from Xcode 26.3.0 → 26.6.0.

Unblocks `[ios] react-native-enriched-markdown`, which fails on 26.3 with `redefinition of module 'RaTeXFFI'` ([run](https://github.com/react-native-community/nightly-tests/actions/runs/29633686007/job/88052074654)).

The library-side fix is already shipped in [software-mansion/react-native-enriched-markdown#546](https://github.com/software-mansion/react-native-enriched-markdown/pull/546) (`SWIFT_ENABLE_EXPLICIT_MODULES=NO`), but Xcode 26.3 still ignores that opt-out; 26.6 respects it.

## Test plan

- [ ] Confirm runners expose Xcode 26.6
- [ ] Verify `[ios] react-native-enriched-markdown` is green on the next Check Nightlies run

### CODE REVIEW

**Comment by hryhoriiK97** [comment]
Closing this - the upstream fix in react-native-enriched-markdown (#546, SWIFT_ENABLE_EXPLICIT_MODULES=NO) has been reverted in software-mansion/react-native-enriched-markdown#551 since it didn't reliably work on Xcode 26.3. The author plans to fix the problem in RN itself. No Xcode bump needed on our side for now.
